#ifndef CONSTANT_H
#define CONSTANT_H


#define ADMINISTRATOR_NUM 0
#define USER_NUM 1

#define LOGINCHECK_SUCCESS 0
#define LOGINCHECK_NOQUEST 1
#define LOGINCHECK_UNMATCH 2

#define BUG qDebug() << "THERE'S A BUG!"
#endif // CONSTANT_H
